version: '3.7'

services:
    db:
        image: mariadb:10.11
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret123
            MYSQL_DATABASE: blog
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - "database_data:/var/lib/mysql:rw"
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - db
    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
volumes:
    database_data:
