version: '3'

services:
    php:
        build: .docker/php
        ports:
            - "${APP_PORT:-81}:80"
        volumes:
            - "./:/app"
        depends_on:
            - db
    php-cli:
        build: .docker/php
        volumes:
            - "./:/app"
        depends_on:
            - db
        entrypoint: php /app/artisan queue:work
    db:
        image: mariadb:10.11
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret123
            MYSQL_DATABASE: ${DB_DATABASE:-blog}
            MYSQL_USER: ${DB_USERNAME:-user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - "database_data:/var/lib/mysql:rw"
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - db
    mailpit:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
volumes:
    database_data:
